theme: jekyll-theme-hacker

title: Fernando Pradas
description: Senior Backend Engineer

logo: https://github.com/fnandot/website/raw/master/profile.png


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
