remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Fernando Pradas
description: Senior Remote Backend Engineer

logo: https://github.com/fnandot/website/raw/master/profile.jpg
