remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Fernando Pradas
description: Senior Remote Backend Engineer

logo: https://pbs.twimg.com/profile_images/1550257321061777413/kk5VBD_i_400x400.jpg
